CREATE DATABASE dbcar;
USE dbcar;
CREATE TABLE RENTER (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    CONTACT VARCHAR(12) NOT NULL);

CREATE TABLE CAR(
	CARNO VARCHAR(20) PRIMARY KEY,
	CARNAME VARCHAR(50) NOT NULL,
    CARMF VARCHAR(50) NOT NULL,
    CARYEAR INT(4) NOT NULL,
    CARSTATUS ENUM('YES','NO') NOT NULL DEFAULT 'YES');
    
CREATE TABLE CUST(
	CUSTID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTNAME VARCHAR(50) NOT NULL,
    CUSTEMAIL VARCHAR(30) NOT NULL,
    CUSTPASS VARCHAR(30) NOT NULL,
    CUSTCONTACT VARCHAR(12) NOT NULL);
CREATE TABLE RENTCAR(
	CARNO VARCHAR(20) NOT NULL,
    CUSTID INT NOT NULL,
    CUSTNAME VARCHAR(50) NOT NULL,
    RETURNSTAT ENUM('YES','NO') NOT NULL DEFAULT 'NO');